import { ConceptNode } from './types';

export const SQL_CONCEPTS: Record<string, ConceptNode> = {
  'select_where': {
    conceptId: 'select_where',
    name: 'SELECT & WHERE',
    description: 'Basic row retrieval, column selection, and conditional filtering using logical operators.',
    type: 'fundamental',
    prerequisites: [],
    children: ['aggregation', 'inner_join'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [1, 1],
    commonErrors: ['syntax_error', 'incorrect_filtering', 'wrong_comparison_operator', 'null_handling_error'],
  },
  'aggregation': {
    conceptId: 'aggregation',
    name: 'Aggregation',
    description: 'Summarizing data using aggregate functions like COUNT, SUM, AVG, MIN, and MAX.',
    type: 'fundamental',
    prerequisites: ['select_where'],
    children: ['group_by'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [1, 2],
    commonErrors: ['aggregation_misuse', 'wrong_aggregate_function', 'null_handling_error'],
  },
  'group_by': {
    conceptId: 'group_by',
    name: 'GROUP BY',
    description: 'Grouping aggregated metrics across dynamic dimensions and non-aggregated select columns.',
    type: 'intermediate',
    prerequisites: ['aggregation'],
    children: ['having'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [1, 2],
    commonErrors: ['missing_group_by', 'incorrect_group_by', 'aggregation_misuse'],
  },
  'having': {
    conceptId: 'having',
    name: 'HAVING Clause',
    description: 'Filtering aggregate results after grouping vs WHERE filtering before aggregation.',
    type: 'intermediate',
    prerequisites: ['group_by'],
    children: ['subqueries'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 2],
    commonErrors: ['where_vs_having', 'aggregation_misuse'],
  },
  'inner_join': {
    conceptId: 'inner_join',
    name: 'INNER JOIN',
    description: 'Combining records from two or more tables based on matching key values.',
    type: 'fundamental',
    prerequisites: ['select_where'],
    children: ['left_join', 'join_conditions'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [1, 2],
    commonErrors: ['wrong_join_type', 'missing_join_condition', 'unexpected_row_multiplication'],
  },
  'left_join': {
    conceptId: 'left_join',
    name: 'LEFT OUTER JOIN',
    description: 'Retaining all left table records while matching optional right table attributes.',
    type: 'intermediate',
    prerequisites: ['inner_join'],
    children: ['join_conditions'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [1, 2],
    commonErrors: ['wrong_join_type', 'null_handling_error', 'incorrect_join_condition'],
  },
  'join_conditions': {
    conceptId: 'join_conditions',
    name: 'JOIN Conditions & ON Filters',
    description: 'Disambiguating primary/foreign keys and understanding filter placement in ON vs WHERE.',
    type: 'intermediate',
    prerequisites: ['inner_join', 'left_join'],
    children: ['subqueries', 'window_functions'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 3],
    commonErrors: ['incorrect_join_condition', 'missing_join_condition', 'duplicate_rows'],
  },
  'subqueries': {
    conceptId: 'subqueries',
    name: 'Subqueries & Nested Queries',
    description: 'Using scalar, column, and correlated subqueries within SELECT, FROM, or WHERE clauses.',
    type: 'intermediate',
    prerequisites: ['group_by', 'join_conditions'],
    children: ['ctes'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 3],
    commonErrors: ['incorrect_subquery_logic', 'subquery_scope_error', 'duplicate_rows'],
  },
  'ctes': {
    conceptId: 'ctes',
    name: 'Common Table Expressions (CTEs)',
    description: 'Modularizing complex query logic with readable WITH clause temporary result sets.',
    type: 'advanced',
    prerequisites: ['subqueries'],
    children: ['window_functions'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 3],
    commonErrors: ['cte_reference_error', 'cte_structure_error'],
  },
  'window_functions': {
    conceptId: 'window_functions',
    name: 'Window Functions',
    description: 'Performing analytical calculations across set partitions without collapsing rows.',
    type: 'advanced',
    prerequisites: ['group_by', 'join_conditions'],
    children: ['row_number_rank', 'partition_by'],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 3],
    commonErrors: ['window_partition_error', 'window_order_error', 'wrong_window_function'],
  },
  'row_number_rank': {
    conceptId: 'row_number_rank',
    name: 'ROW_NUMBER vs RANK vs DENSE_RANK',
    description: 'Applying appropriate sequence ranking functions based on tie-handling requirements.',
    type: 'advanced',
    prerequisites: ['window_functions'],
    children: [],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [2, 3],
    commonErrors: ['wrong_window_function', 'window_order_error'],
  },
  'partition_by': {
    conceptId: 'partition_by',
    name: 'PARTITION BY & ORDER BY',
    description: 'Definining framing partitions and window sorting order for moving averages & cumulative sums.',
    type: 'advanced',
    prerequisites: ['window_functions'],
    children: [],
    supportedSkills: ['recognition', 'reasoning', 'diagnosis', 'correction', 'implementation'],
    difficultyRange: [3, 3],
    commonErrors: ['window_partition_error', 'window_order_error'],
  },
};
